service: upnext-api

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 4000

functions:
  graphql:
    handler: src/handler.graphql
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get

resources:
  Resources:
    UserTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: 'Tasks'
        KeySchema:
          - 
            AttributeName: id
            KeyType: HASH
        AttributeDefinitions:
          - 
            AttributeName: title
            AttributeType: S
        BillingMode: PAY_PER_REQUEST