-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Mutation exposing (CreateTaskRequiredArguments, createTask)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


type alias CreateTaskRequiredArguments =
    { title : String }


{-|

  - title -

-}
createTask : CreateTaskRequiredArguments -> SelectionSet decodesTo Api.Object.Task -> SelectionSet decodesTo RootMutation
createTask requiredArgs object_ =
    Object.selectionForCompositeField "createTask" [ Argument.required "title" requiredArgs.title Encode.string ] object_ identity
